USE cpss;

DROP TABLE IF EXISTS `county` ;

CREATE TABLE IF NOT EXISTS `county` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `county` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `ID` (`id`)
) ;

LOCK TABLES `county` WRITE;
/*!40000 ALTER TABLE `county` DISABLE KEYS */;
INSERT `county` (`id`, `county`) VALUES
	(NULL, 'Adams'),
	(NULL, 'Allegheny'),
	(NULL, 'Armstrong'),
	(NULL, 'Beaver'),
	(NULL, 'Bedford'),
	(NULL, 'Berks'),
	(NULL, 'Blair'),
	(NULL, 'Bradford'),
	(NULL, 'Bucks'),
	(NULL, 'Butler'),
	(NULL, 'Cambria'),
	(NULL, 'Cameron'),
	(NULL, 'Carbon'),
	(NULL, 'Centre'),
	(NULL, 'Chester'),
	(NULL, 'Clarion'),
	(NULL, 'Clearfield'),
	(NULL, 'Clinton'),
	(NULL, 'Columbia'),
	(NULL, 'Crawford'),
	(NULL, 'Cumberland'),
	(NULL, 'Dauphin'),
	(NULL, 'Delaware'),
	(NULL, 'Elk'),
	(NULL, 'Erie'),
	(NULL, 'Fayette'),
	(NULL, 'Forest'),
	(NULL, 'Franklin'),
	(NULL, 'Fulton'),
	(NULL, 'Greene'),
	(NULL, 'Huntingdon'),
	(NULL, 'Indiana'),
	(NULL, 'Jefferson'),
	(NULL, 'Juniata'),
	(NULL, 'Lackawanna'),
	(NULL, 'Lancaster'),
	(NULL, 'Lawrence'),
	(NULL, 'Lebanon'),
	(NULL, 'Lehigh'),
	(NULL, 'Luzerne'),
	(NULL, 'Lycoming'),
	(NULL, 'McKean'),
	(NULL, 'Mercer'),
	(NULL, 'Mifflin'),
	(NULL, 'Monroe'),
	(NULL, 'Montgomery'),
	(NULL, 'Montour'),
	(NULL, 'Northampton'),
	(NULL, 'Northumberland'),
	(NULL, 'Perry'),
	(NULL, 'Philadelphia'),
	(NULL, 'Pike'),
	(NULL, 'Potter'),
	(NULL, 'Schuylkill'),
	(NULL, 'Snyder'),
	(NULL, 'Somerset'),
	(NULL, 'Sullivan'),
	(NULL, 'Susquehanna'),
	(NULL, 'Tioga'),
	(NULL, 'Union'),
	(NULL, 'Venango'),
	(NULL, 'Warren'),
	(NULL, 'Washington'),
	(NULL, 'Wayne'),
	(NULL, 'Westmoreland'),
	(NULL, 'Wyoming'),
	(NULL, 'York') ;
/*!40000 ALTER TABLE `county` ENABLE KEYS */;
UNLOCK TABLES;

