USE cpss;

DROP TABLE IF EXISTS dia;

CREATE TABLE IF NOT EXISTS dia(
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `ID` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ;

LOCK TABLES `dia` WRITE;
/*!40000 ALTER TABLE `dia` DISABLE KEYS */;
INSERT INTO `dia` VALUES (1,'F79'),(2,'F70'),(3,'F71'),(6,'F72');
/*!40000 ALTER TABLE `dia` ENABLE KEYS */;
UNLOCK TABLES;

